---
title: "Selection Coefficients"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(viridis)
library(colorspace)
library(gridExtra)
library(tidyverse)
require(reshape2)
library(plyr)
```

## My Goals

The goal of this experiment is to see if there is a link between the phenotype of a newt or snake and its ability to survive. This prediction stems from the idea that if a phenotype is higher in a newt or snake, the individual will survive an interaction with the opposite species. To look at this I will calculate the correlation between an individuals phenotype and an individuals SLiM fitnessScaling. There are some potential problems with this calculation, like space (some areas one phenotype might be beneficial, but it others not) and that the interaction is not very strong. 

Beta calculation for the Newt: beta_n = cor(phenotypes_n, inds_n.fitnessScaling);
Beta calculation for the Snake:	beta_s = cor(phenotypes_s, inds_s.fitnessScaling);
**Must be calculated in early. fitnessScaling set to 0 if newt or snake is killed by the opposite species, but what about interspecific interactions (density dependence)**




## The interaction of Newts and Snakes

I was wondering how often newts and snakes interact in a SLiMulation so I had SLiM print out four values, snake_found_newt (when a snake was potentially able to find  a newt), newt_found (a snake found a newt), snake_deaths (snakes that were killed by newts), and newt_deaths (newts that were eaten by snakes). I also added the population size for newts and snakes to see in the number of interactions depend on the population size - which is linked to density. It looks like one the population size stabilizes (around 100 generations) there are 30-60 interactions each generation. Today 8/30/2021 I will run 20 of the same simulation to see if I can get a consensus on how many times newts and snake interact in each generation. Once I get this value I can plug it into nospace.slim to compare the results of the same simulation to a simulation with a lack of space. This will hopefully help me understand how space effects the coevolution of newts and snakes   


## No Space SLiM Results

